services:
  dashboard:
    build: .
    container_name: pri_dashboard
    volumes:
      - ./data:/app/data
    ports:
      - "${HOST_IP:-0.0.0.0}:8517:8517"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
